Handling git clonefork curl errors more gracefully
Signed-off-by: Cali0707 <calumramurray@gmail.com>

diff --git a/git-clonefork b/git-clonefork
--- a/git-clonefork
+++ b/git-clonefork
@@ -14,14 +14,35 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-GIT_ORIGIN=$1
-REPO_DIRECTORY=$(basename $GIT_ORIGIN .git)
-GITHUB_API_URL=$(echo $GIT_ORIGIN | sed -r 's/.*(\@|\/\/)(.*)(\:|\/)([^:\/]*)\/([^\/\.]*)\.git/https:\/\/api.github.com\/repos\/\4\/\5/')
-if grep -Eiq "^https?://" <<<$GIT_ORIGIN; then
-	UPSTREAM_ORIGIN=$(curl -s $GITHUB_API_URL | jq -r .parent.clone_url)
-else
-	UPSTREAM_ORIGIN=$(curl -s $GITHUB_API_URL | jq -r .parent.ssh_url)
+if [[ -z $1 ]]; then
+    echo "Please provide a fork url"
+    echo "usage: git clonefork <fork_url>"
+    exit 2
 fi
+
+GIT_ORIGIN=$1
+# get the name of the directory that will be created when we clone
+REPO_DIRECTORY=$(basename $GIT_ORIGIN .git)
+# reformat the repo url into a github api request
+GITHUB_API_URL=$(echo $GIT_ORIGIN | sed -r 's/.*(\@|\/\/)(.*)(\:|\/)([^:\/]*)\/([^\/\.]*)\.git/https:\/\/api.github.com\/repos\/\4\/\5/')
+
+# make the api request and validate we get a good response
+# -f makes curl fail silently, so REPO_DATA will be null on failure
+REPO_DATA=$(curl -fs $GITHUB_API_URL)
+if [[ -z $REPO_DATA ]]; then
+    echo "Please provide a valid fork url"
+    echo "usage: git clonefork <fork_url>"
+    exit 2
+fi
+
+if grep -Eiq "^https?://" <<<$GIT_ORIGIN; then
+    # we aren't cloning with ssh, use the default parent clone_url
+	UPSTREAM_ORIGIN=$(echo $REPO_DATA | jq -r .parent.clone_url)
+else
+    # we want to clone with ssh
+	UPSTREAM_ORIGIN=$(echo $REPO_DATA | jq -r .parent.ssh_url)
+fi
+
 git clone $GIT_ORIGIN
 cd $REPO_DIRECTORY
 git remote add upstream $UPSTREAM_ORIGIN
